- name: variables from file 
  hosts: local
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "course {{ course }}, duration {{  DURATION }}, and the trainer is {{ TRAINER }}"