- name: install packeges using loop
  hosts: local
  connection: local
  become: true
  tasks:
  - name: print names
    ansible.builtin.package:
      msg: "{{ item }}"
    loop:
      - nginx
      - mysql
       